### ISSUE TITLE
Squared variance

### ISSUE THREAD

**Issue by peterbjorgensen** [AMLab-Amsterdam/MNF_VBNN#2]
In this line Vtilde becomes the square of the variance. I think it should just be the variance?

https://github.com/AMLab-Amsterdam/MNF_VBNN/blob/c24c256ca7cae88216013924dac5087db8f24730/dense_layers.py#L104

**Comment by clouizos** [comment]
This is just a bad naming of the variables on my part; Vtilde is in fact the variance. Notice that in the call function:

    def call(self, x, sample=True, **kwargs):
        std_mg = tf.clip_by_value(self.get_params_W(), 0., self.thres_var)
        var_mg = tf.square(std_mg)

we also take the square of self.get_params_W() to get the variance as well. As a result, self.logvar_W represents the log of the standard deviation.
