### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mhavasi** [AMLab-Amsterdam/MNF_VBNN#3]
Hey,

I would like to use this code for a project. Could you add a license to it?

**Comment by mhavasi** [comment]
You may not be aware of this, but legally, without a license, no one can use your code.

http://opensource.stackexchange.com/q/1720/775

**Comment by clouizos** [comment]
Thanks for bringing this into my attention, I have now added a licence to the repo.

**Comment by mhavasi** [comment]
Nice, thanks for the quick reply! :)
