### ISSUE TITLE
Clarification about the use_z argument

### ISSUE THREAD

**Issue by sayantanauddy** [AMLab-Amsterdam/MNF_VBNN#5]
When we say that `use_z=False` when initializing a layer, does that layer behave like a Fully factored Gaussian layer? I saw that the `logrm` and `logqm` terms in the `kldiv` function are set to 0 when  `use_z=False`, but I still wanted to confirm if my understanding is correct.

**Comment by clouizos** [comment]
Hi,

Yes that is indeed true. I will be closing this issue and the issue tracker as this repo is provided as is and not maintained any more.
